export const LOAD_DATA ="LOAD_DATA";
export const LOAD_TLE_GRID ="LOAD_TLE_GRID";
export const SIGNAL_TLE_GRID_LOAD_SUCCESS ="SIGNAL_TLE_GRID_LOAD_SUCCESS";
export const LOAD_TLE_DETAILS ="LOAD_TLE_DETAILS";
export const LOAD_ERROR ="LOAD_ERROR";
export const SELECT_GRID_ITEM="SELECT_GRID_ITEM";
